/*
 Copyright (c) 2010 Arc90 Inc
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
//Based on Arc90's readability.js (1.7.1) available at: http://code.google.com/p/arc90labs-readability
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,c){a.raw=c;return a};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};$jscomp.polyfill=function(a,c,b,d){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,d):$jscomp.polyfillUnisolated(a,c,b,d))};
$jscomp.polyfillUnisolated=function(a,c,b,d){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in b))return;b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<e.length-1;h++){var f=e[h];if(!(f in d))return;d=d[f]}e=e[e.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?d[e]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:c}):c!==b&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(b=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+b+"$"+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:c})))};
$jscomp.polyfill("Array.from",function(a){return a?a:function(c,b,d){b=null!=b?b:function(m){return m};var e=[],h="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];if("function"==typeof h){c=h.call(c);for(var f=0;!(h=c.next()).done;)e.push(b.call(d,h.value,f++))}else for(h=c.length,f=0;f<h;f++)e.push(b.call(d,c[f],f));return e}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},c=Object.create(new $jscomp.global.Proxy(a,{get:function(b,d,e){return b==a&&"q"==d&&e==c}}));return!0===c.q}catch(b){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var c=function(h,f){this.$jscomp$symbol$id_=h;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};c.prototype.toString=function(){return this.$jscomp$symbol$id_};var b="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(h){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new c(b+(h||"")+"_"+d++,h)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var c="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),b=0;b<c.length;b++){var d=$jscomp.global[c[b]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.owns=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};
$jscomp.polyfill("WeakMap",function(a){function c(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),n=new a([[k,2],[l,3]]);if(2!=n.get(k)||3!=n.get(l))return!1;n.delete(k);n.set(l,4);return!n.has(k)&&4==n.get(l)}catch(q){return!1}}function b(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!$jscomp.owns(k,f)){var l=new b;$jscomp.defineProperty(k,f,{value:l})}}function h(k){if(!$jscomp.ISOLATE_POLYFILLS){var l=Object[k];l&&(Object[k]=
function(n){if(n instanceof b)return n;Object.isExtensible(n)&&e(n);return l(n)})}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(c())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var m=0,g=function(k){this.id_=(m+=Math.random()+1).toString();if(k){k=$jscomp.makeIterator(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");
e(k);if(!$jscomp.owns(k,f))throw Error("WeakMap key fail: "+k);k[f][this.id_]=l;return this};g.prototype.get=function(k){return d(k)&&$jscomp.owns(k,f)?k[f][this.id_]:void 0};g.prototype.has=function(k){return d(k)&&$jscomp.owns(k,f)&&$jscomp.owns(k[f],this.id_)};g.prototype.delete=function(k){return d(k)&&$jscomp.owns(k,f)&&$jscomp.owns(k[f],this.id_)?delete k[f][this.id_]:!1};return g},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function c(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),k=new a($jscomp.makeIterator([[g,"s"]]));if("s"!=k.get(g)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),n=l.next();if(n.done||n.value[0]!=g||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!l.next().done?!1:!0}catch(q){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(c())return a;var b=new WeakMap,d=function(g){this.data_={};this.head_=f();this.size=0;if(g){g=$jscomp.makeIterator(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};d.prototype.set=function(g,k){g=0===g?0:g;var l=e(this,g);l.list||(l.list=this.data_[l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:g,value:k},l.list.push(l.entry),
this.head_.previous.next=l.entry,this.head_.previous=l.entry,this.size++);return this};d.prototype.delete=function(g){g=e(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.data_[g.id],g.entry.previous.next=g.entry.next,g.entry.next.previous=g.entry.previous,g.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=f();this.size=0};d.prototype.has=function(g){return!!e(this,g).entry};d.prototype.get=function(g){return(g=
e(this,g).entry)&&g.value};d.prototype.entries=function(){return h(this,function(g){return[g.key,g.value]})};d.prototype.keys=function(){return h(this,function(g){return g.key})};d.prototype.values=function(){return h(this,function(g){return g.value})};d.prototype.forEach=function(g,k){for(var l=this.entries(),n;!(n=l.next()).done;)n=n.value,g.call(k,n[1],n[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(g,k){var l=k&&typeof k;"object"==l||"function"==l?b.has(k)?l=b.get(k):
(l=""+ ++m,b.set(k,l)):l="p_"+k;var n=g.data_[l];if(n&&$jscomp.owns(g.data_,l))for(g=0;g<n.length;g++){var q=n[g];if(k!==k&&q.key!==q.key||k===q.key)return{id:l,list:n,index:g,entry:q}}return{id:l,list:n,index:-1,entry:void 0}},h=function(g,k){var l=g.head_;return $jscomp.iteratorPrototype(function(){if(l){for(;l.head!=g.head_;)l=l.previous;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.previous=g.next=g.head=g},m=0;
return d},"es6","es3");
$jscomp.polyfill("Set",function(a){function c(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),e=new a($jscomp.makeIterator([d]));if(!e.has(d)||1!=e.size||e.add(d)!=e||1!=e.size||e.add({x:4})!=e||2!=e.size)return!1;var h=e.entries(),f=h.next();if(f.done||f.value[0]!=d||f.value[1]!=d)return!1;f=h.next();return f.done||f.value[0]==d||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:h.next().done}catch(m){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(c())return a;var b=function(d){this.map_=new Map;if(d){d=$jscomp.makeIterator(d);for(var e;!(e=d.next()).done;)this.add(e.value)}this.size=this.map_.size};b.prototype.add=function(d){d=0===d?0:d;this.map_.set(d,d);this.size=this.map_.size;return this};b.prototype.delete=function(d){d=this.map_.delete(d);this.size=this.map_.size;return d};b.prototype.clear=function(){this.map_.clear();this.size=0};b.prototype.has=
function(d){return this.map_.has(d)};b.prototype.entries=function(){return this.map_.entries()};b.prototype.values=function(){return this.map_.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(d,e){var h=this;this.map_.forEach(function(f){return d.call(e,f,f,h)})};return b},"es6","es3");
$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var h=a[e];if(c.call(b,h,e,a))return{i:e,v:h}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(c,b){return $jscomp.findInternal(this,c,b).v}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(c,b){return c===b?0!==c||1/c===1/b:c!==c&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(c,b){var d=this;d instanceof String&&(d=String(d));var e=d.length;b=b||0;for(0>b&&(b=Math.max(b+e,0));b<e;b++){var h=d[b];if(h===c||Object.is(h,c))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,c,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(c,b){return-1!==$jscomp.checkStringArgs(this,c,"includes").indexOf(c,b||0)}},"es6","es3");
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(c,b){var d=$jscomp.checkStringArgs(this,c,"startsWith");c+="";var e=d.length,h=c.length;b=Math.max(0,Math.min(b|0,d.length));for(var f=0;f<h&&b<e;)if(d[b++]!=c[f++])return!1;return f>=h}},"es6","es3");
function Readability(a,c,b){if(c&&c.documentElement)a=c,c=b;else if(!a||!a.documentElement)throw Error("First argument to Readability constructor should be a document object.");c=c||{};this._doc=a;this._docJSDOMParser=this._doc.firstChild.__JSDOMParser__;this._articleSiteName=this._articleDir=this._articleByline=this._articleTitle=null;this._attempts=[];this._debug=!!c.debug;this._maxElemsToParse=c.maxElemsToParse||this.DEFAULT_MAX_ELEMS_TO_PARSE;this._nbTopCandidates=c.nbTopCandidates||this.DEFAULT_N_TOP_CANDIDATES;
this._charThreshold=c.charThreshold||this.DEFAULT_CHAR_THRESHOLD;this._classesToPreserve=this.CLASSES_TO_PRESERVE.concat(c.classesToPreserve||[]);this._keepClasses=!!c.keepClasses;this._serializer=c.serializer||function(e){return e.innerHTML};this._disableJSONLD=!!c.disableJSONLD;this._flags=this.FLAG_STRIP_UNLIKELYS|this.FLAG_WEIGHT_CLASSES|this.FLAG_CLEAN_CONDITIONALLY;if(this._debug){var d=function(e){if(e.nodeType==e.TEXT_NODE)return e.nodeName+' ("'+e.textContent+'")';var h=Array.from(e.attributes||
[],function(f){return f.name+'="'+f.value+'"'}).join(" ");return"<"+e.localName+" "+h+">"};this.log=function(){var e=this;if("undefined"!==typeof dump){var h=Array.prototype.map.call(arguments,function(f){return f&&f.nodeName?d(f):f}).join(" ");dump("Reader: (Readability) "+h+"\n")}else"undefined"!==typeof console&&(h=Array.from(arguments,function(f){return f&&f.nodeType==e.ELEMENT_NODE?d(f):f}),h.unshift("Reader: (Readability)"),console.log.apply(console,h))}}else this.log=function(){}}
Readability.prototype={FLAG_STRIP_UNLIKELYS:1,FLAG_WEIGHT_CLASSES:2,FLAG_CLEAN_CONDITIONALLY:4,ELEMENT_NODE:1,TEXT_NODE:3,DEFAULT_MAX_ELEMS_TO_PARSE:0,DEFAULT_N_TOP_CANDIDATES:5,DEFAULT_TAGS_TO_SCORE:"SECTION H2 H3 H4 H5 H6 P TD PRE".split(" "),DEFAULT_CHAR_THRESHOLD:500,REGEXPS:{unlikelyCandidates:/-ad-|ai2html|banner|breadcrumbs|combx|comment|community|cover-wrap|disqus|extra|footer|gdpr|header|legends|menu|related|remark|replies|rss|shoutbox|sidebar|skyscraper|social|sponsor|supplemental|ad-break|agegate|pagination|pager|popup|yom-remote/i,
okMaybeItsACandidate:/and|article|body|column|content|main|shadow/i,positive:/article|body|content|entry|hentry|h-entry|main|page|pagination|post|text|blog|story/i,negative:/-ad-|hidden|^hid$| hid$| hid |^hid |banner|combx|comment|com-|contact|foot|footer|footnote|gdpr|masthead|media|meta|outbrain|promo|related|scroll|share|shoutbox|sidebar|skyscraper|sponsor|shopping|tags|tool|widget/i,extraneous:/print|archive|comment|discuss|e[\-]?mail|share|reply|all|login|sign|single|utility/i,byline:/byline|author|dateline|writtenby|p-author/i,
replaceFonts:/<(\/?)font[^>]*>/gi,normalize:/\s{2,}/g,videos:/\/\/(www\.)?((dailymotion|youtube|youtube-nocookie|player\.vimeo|v\.qq)\.com|(archive|upload\.wikimedia)\.org|player\.twitch\.tv)/i,shareElements:/(\b|_)(share|sharedaddy)(\b|_)/i,nextLink:/(next|weiter|continue|>([^\|]|$)|\u00bb([^\|]|$))/i,prevLink:/(prev|earl|old|new|<|\u00ab)/i,tokenize:/\W+/g,whitespace:/^\s*$/,hasContent:/\S$/,hashUrl:/^#.+/,srcsetUrl:/(\S+)(\s+[\d.]+[xw])?(\s*(?:,|$))/g,b64DataUrl:/^data:\s*([^\s;,]+)\s*;\s*base64\s*,/i,
jsonLdArticleTypes:/^Article|AdvertiserContentArticle|NewsArticle|AnalysisNewsArticle|AskPublicNewsArticle|BackgroundNewsArticle|OpinionNewsArticle|ReportageNewsArticle|ReviewNewsArticle|Report|SatiricalArticle|ScholarlyArticle|MedicalScholarlyArticle|SocialMediaPosting|BlogPosting|LiveBlogPosting|DiscussionForumPosting|TechArticle|APIReference$/},UNLIKELY_ROLES:"menu menubar complementary navigation alert alertdialog dialog".split(" "),DIV_TO_P_ELEMS:new Set("BLOCKQUOTE DL DIV IMG OL P PRE TABLE UL".split(" ")),
ALTER_TO_DIV_EXCEPTIONS:["DIV","ARTICLE","SECTION","P"],PRESENTATIONAL_ATTRIBUTES:"align background bgcolor border cellpadding cellspacing frame hspace rules style valign vspace".split(" "),DEPRECATED_SIZE_ATTRIBUTE_ELEMS:["TABLE","TH","TD","HR","PRE"],PHRASING_ELEMS:"ABBR AUDIO B BDO BR BUTTON CITE CODE DATA DATALIST DFN EM EMBED I IMG INPUT KBD LABEL MARK MATH METER NOSCRIPT OBJECT OUTPUT PROGRESS Q RUBY SAMP SCRIPT SELECT SMALL SPAN STRONG SUB SUP TEXTAREA TIME VAR WBR".split(" "),CLASSES_TO_PRESERVE:["page"],
HTML_ESCAPE_MAP:{lt:"<",gt:">",amp:"&",quot:'"',apos:"'"},_postProcessContent:function(a){this._fixRelativeUris(a);this._simplifyNestedElements(a);this._keepClasses||this._cleanClasses(a)},_removeNodes:function(a,c){if(this._docJSDOMParser&&a._isLiveNodeList)throw Error("Do not pass live node lists to _removeNodes");for(var b=a.length-1;0<=b;b--){var d=a[b],e=d.parentNode;e&&(!c||c.call(this,d,b,a))&&e.removeChild(d)}},_replaceNodeTags:function(a,c){if(this._docJSDOMParser&&a._isLiveNodeList)throw Error("Do not pass live node lists to _replaceNodeTags");
a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())this._setNodeTag(b.value,c)},_forEachNode:function(a,c){Array.prototype.forEach.call(a,c,this)},_findNode:function(a,c){return Array.prototype.find.call(a,c,this)},_someNode:function(a,c){return Array.prototype.some.call(a,c,this)},_everyNode:function(a,c){return Array.prototype.every.call(a,c,this)},_concatNodeLists:function(){var a=Array.prototype.slice,c=a.call(arguments).map(function(b){return a.call(b)});return Array.prototype.concat.apply([],
c)},_getAllNodesWithTag:function(a,c){return a.querySelectorAll?a.querySelectorAll(c.join(",")):[].concat.apply([],c.map(function(b){b=a.getElementsByTagName(b);return Array.isArray(b)?b:Array.from(b)}))},_cleanClasses:function(a){var c=this._classesToPreserve,b=(a.getAttribute("class")||"").split(/\s+/).filter(function(d){return-1!=c.indexOf(d)}).join(" ");b?a.setAttribute("class",b):a.removeAttribute("class");for(a=a.firstElementChild;a;a=a.nextElementSibling)this._cleanClasses(a)},_fixRelativeUris:function(a){function c(h){if(b==
d&&"#"==h.charAt(0))return h;try{return(new URL(h,b)).href}catch(f){}return h}var b=this._doc.baseURI,d=this._doc.documentURI,e=this._getAllNodesWithTag(a,["a"]);this._forEachNode(e,function(h){var f=h.getAttribute("href");if(f)if(0===f.indexOf("javascript:"))if(1===h.childNodes.length&&h.childNodes[0].nodeType===this.TEXT_NODE)f=this._doc.createTextNode(h.textContent),h.parentNode.replaceChild(f,h);else{for(f=this._doc.createElement("span");h.firstChild;)f.appendChild(h.firstChild);h.parentNode.replaceChild(f,
h)}else h.setAttribute("href",c(f))});a=this._getAllNodesWithTag(a,"img picture figure video audio source".split(" "));this._forEachNode(a,function(h){var f=h.getAttribute("src"),m=h.getAttribute("poster"),g=h.getAttribute("srcset");f&&h.setAttribute("src",c(f));m&&h.setAttribute("poster",c(m));g&&(f=g.replace(this.REGEXPS.srcsetUrl,function(k,l,n,q){return c(l)+(n||"")+q}),h.setAttribute("srcset",f))})},_simplifyNestedElements:function(a){for(;a;){if(a.parentNode&&["DIV","SECTION"].includes(a.tagName)&&
(!a.id||!a.id.startsWith("readability")))if(this._isElementWithoutContent(a)){a=this._removeAndGetNext(a);continue}else if(this._hasSingleTagInsideElement(a,"DIV")||this._hasSingleTagInsideElement(a,"SECTION")){for(var c=a.children[0],b=0;b<a.attributes.length;b++)c.setAttribute(a.attributes[b].name,a.attributes[b].value);a.parentNode.replaceChild(c,a);a=c;continue}a=this._getNextNode(a)}},_getArticleTitle:function(){function a(f){return f.split(/\s+/).length}var c=this._doc,b="",d="";try{b=d=c.title.trim(),
"string"!==typeof b&&(b=d=this._getInnerText(c.getElementsByTagName("title")[0]))}catch(f){}var e=!1;if(/ [\|\-\\\/>\u00bb] /.test(b))e=/ [\\\/>\u00bb] /.test(b),b=d.replace(/(.*)[\|\-\\\/>\u00bb] .*/gi,"$1"),3>a(b)&&(b=d.replace(/[^\|\-\\\/>\u00bb]*[\|\-\\\/>\u00bb](.*)/gi,"$1"));else if(-1!==b.indexOf(": ")){c=this._concatNodeLists(c.getElementsByTagName("h1"),c.getElementsByTagName("h2"));var h=b.trim();this._someNode(c,function(f){return f.textContent.trim()===h})||(b=d.substring(d.lastIndexOf(":")+
1),3>a(b)?b=d.substring(d.indexOf(":")+1):5<a(d.substr(0,d.indexOf(":")))&&(b=d))}else if(150<b.length||15>b.length)c=c.getElementsByTagName("h1"),1===c.length&&(b=this._getInnerText(c[0]));b=b.trim().replace(this.REGEXPS.normalize," ");c=a(b);4>=c&&(!e||c!=a(d.replace(/[\|\-\\\/>\u00bb]+/g,""))-1)&&(b=d);return b},_prepDocument:function(){var a=this._doc;this._removeNodes(this._getAllNodesWithTag(a,["style"]));a.body&&this._replaceBrs(a.body);this._replaceNodeTags(this._getAllNodesWithTag(a,["font"]),
"SPAN")},_nextNode:function(a){for(;a&&a.nodeType!=this.ELEMENT_NODE&&this.REGEXPS.whitespace.test(a.textContent);)a=a.nextSibling;return a},_replaceBrs:function(a){this._forEachNode(this._getAllNodesWithTag(a,["br"]),function(c){for(var b=c.nextSibling,d=!1;(b=this._nextNode(b))&&"BR"==b.tagName;){d=!0;var e=b.nextSibling;b.parentNode.removeChild(b);b=e}if(d){d=this._doc.createElement("p");c.parentNode.replaceChild(d,c);for(b=d.nextSibling;b&&("BR"!=b.tagName||!(c=this._nextNode(b.nextSibling))||
"BR"!=c.tagName)&&this._isPhrasingContent(b);)c=b.nextSibling,d.appendChild(b),b=c;for(;d.lastChild&&this._isWhitespace(d.lastChild);)d.removeChild(d.lastChild);"P"===d.parentNode.tagName&&this._setNodeTag(d.parentNode,"DIV")}})},_setNodeTag:function(a,c){this.log("_setNodeTag",a,c);if(this._docJSDOMParser)return a.localName=c.toLowerCase(),a.tagName=c.toUpperCase(),a;for(c=a.ownerDocument.createElement(c);a.firstChild;)c.appendChild(a.firstChild);a.parentNode.replaceChild(c,a);a.readability&&(c.readability=
a.readability);for(var b=0;b<a.attributes.length;b++)try{c.setAttribute(a.attributes[b].name,a.attributes[b].value)}catch(d){}return c},_prepArticle:function(a){this._cleanStyles(a);this._markDataTables(a);this._fixLazyImages(a);this._cleanConditionally(a,"form");this._cleanConditionally(a,"fieldset");this._clean(a,"object");this._clean(a,"embed");this._clean(a,"footer");this._clean(a,"link");this._clean(a,"aside");var c=this.DEFAULT_CHAR_THRESHOLD;this._forEachNode(a.children,function(b){this._cleanMatchedNodes(b,
function(d,e){return this.REGEXPS.shareElements.test(e)&&d.textContent.length<c})});this._clean(a,"iframe");this._clean(a,"input");this._clean(a,"textarea");this._clean(a,"select");this._clean(a,"button");this._cleanHeaders(a);this._cleanConditionally(a,"table");this._cleanConditionally(a,"ul");this._cleanConditionally(a,"div");this._replaceNodeTags(this._getAllNodesWithTag(a,["h1"]),"h2");this._removeNodes(this._getAllNodesWithTag(a,["p"]),function(b){var d=b.getElementsByTagName("img").length,e=
b.getElementsByTagName("embed").length,h=b.getElementsByTagName("object").length,f=b.getElementsByTagName("iframe").length;return 0===d+e+h+f&&!this._getInnerText(b,!1)});this._forEachNode(this._getAllNodesWithTag(a,["br"]),function(b){var d=this._nextNode(b.nextSibling);d&&"P"==d.tagName&&b.parentNode.removeChild(b)});this._forEachNode(this._getAllNodesWithTag(a,["table"]),function(b){var d=this._hasSingleTagInsideElement(b,"TBODY")?b.firstElementChild:b;this._hasSingleTagInsideElement(d,"TR")&&
(d=d.firstElementChild,this._hasSingleTagInsideElement(d,"TD")&&(d=d.firstElementChild,d=this._setNodeTag(d,this._everyNode(d.childNodes,this._isPhrasingContent)?"P":"DIV"),b.parentNode.replaceChild(d,b)))})},_initializeNode:function(a){a.readability={contentScore:0};switch(a.tagName){case "DIV":a.readability.contentScore+=5;break;case "PRE":case "TD":case "BLOCKQUOTE":a.readability.contentScore+=3;break;case "ADDRESS":case "OL":case "UL":case "DL":case "DD":case "DT":case "LI":case "FORM":a.readability.contentScore-=
3;break;case "H1":case "H2":case "H3":case "H4":case "H5":case "H6":case "TH":a.readability.contentScore-=5}a.readability.contentScore+=this._getClassWeight(a)},_removeAndGetNext:function(a){var c=this._getNextNode(a,!0);a.parentNode.removeChild(a);return c},_getNextNode:function(a,c){if(!c&&a.firstElementChild)return a.firstElementChild;if(a.nextElementSibling)return a.nextElementSibling;do a=a.parentNode;while(a&&!a.nextElementSibling);return a&&a.nextElementSibling},_textSimilarity:function(a,
c){var b=a.toLowerCase().split(this.REGEXPS.tokenize).filter(Boolean);a=c.toLowerCase().split(this.REGEXPS.tokenize).filter(Boolean);return b.length&&a.length?1-a.filter(function(d){return!b.includes(d)}).join(" ").length/a.join(" ").length:0},_checkByline:function(a,c){if(this._articleByline)return!1;if(void 0!==a.getAttribute)var b=a.getAttribute("rel"),d=a.getAttribute("itemprop");return("author"===b||d&&-1!==d.indexOf("author")||this.REGEXPS.byline.test(c))&&this._isValidByline(a.textContent)?
(this._articleByline=a.textContent.trim(),!0):!1},_getNodeAncestors:function(a,c){c=c||0;for(var b=0,d=[];a.parentNode;){d.push(a.parentNode);if(c&&++b===c)break;a=a.parentNode}return d},_grabArticle:function(a){this.log("**** grabArticle ****");var c=this._doc,b=null!==a;a=a?a:this._doc.body;if(!a)return this.log("No body found in document. Abort."),null;for(var d=a.innerHTML;;){this.log("Starting grabArticle loop");for(var e=this._flagIsActive(this.FLAG_STRIP_UNLIKELYS),h=[],f=this._doc.documentElement,
m=!0;f;){var g=f.className+" "+f.id;if(this._isProbablyVisible(f))if(this._checkByline(f,g))f=this._removeAndGetNext(f);else if(m&&this._headerDuplicatesTitle(f))this.log("Removing header: ",f.textContent.trim(),this._articleTitle.trim()),m=!1,f=this._removeAndGetNext(f);else{if(e){if(this.REGEXPS.unlikelyCandidates.test(g)&&!this.REGEXPS.okMaybeItsACandidate.test(g)&&!this._hasAncestorTag(f,"table")&&!this._hasAncestorTag(f,"code")&&"BODY"!==f.tagName&&"A"!==f.tagName){this.log("Removing unlikely candidate - "+
g);f=this._removeAndGetNext(f);continue}if(this.UNLIKELY_ROLES.includes(f.getAttribute("role"))){this.log("Removing content with role "+f.getAttribute("role")+" - "+g);f=this._removeAndGetNext(f);continue}}if("DIV"!==f.tagName&&"SECTION"!==f.tagName&&"HEADER"!==f.tagName&&"H1"!==f.tagName&&"H2"!==f.tagName&&"H3"!==f.tagName&&"H4"!==f.tagName&&"H5"!==f.tagName&&"H6"!==f.tagName||!this._isElementWithoutContent(f)){-1!==this.DEFAULT_TAGS_TO_SCORE.indexOf(f.tagName)&&h.push(f);if("DIV"===f.tagName){g=
null;for(var k=f.firstChild;k;){var l=k.nextSibling;if(this._isPhrasingContent(k))null!==g?g.appendChild(k):this._isWhitespace(k)||(g=c.createElement("p"),f.replaceChild(g,k),g.appendChild(k));else if(null!==g){for(;g.lastChild&&this._isWhitespace(g.lastChild);)g.removeChild(g.lastChild);g=null}k=l}this._hasSingleTagInsideElement(f,"P")&&.25>this._getLinkDensity(f)?(g=f.children[0],f.parentNode.replaceChild(g,f),f=g,h.push(f)):this._hasChildBlockElement(f)||(f=this._setNodeTag(f,"P"),h.push(f))}f=
this._getNextNode(f)}else f=this._removeAndGetNext(f)}else this.log("Removing hidden node - "+g),f=this._removeAndGetNext(f)}var n=[];this._forEachNode(h,function(t){if(t.parentNode&&"undefined"!==typeof t.parentNode.tagName){var x=this._getInnerText(t);if(!(25>x.length)&&(t=this._getNodeAncestors(t,5),0!==t.length)){var y=0;y+=1;y+=x.split(",").length;y+=Math.min(Math.floor(x.length/100),3);this._forEachNode(t,function(v,z){v.tagName&&v.parentNode&&"undefined"!==typeof v.parentNode.tagName&&("undefined"===
typeof v.readability&&(this._initializeNode(v),n.push(v)),v.readability.contentScore+=y/(0===z?1:1===z?2:3*z))})}}});h=[];e=0;for(f=n.length;e<f;e+=1)for(m=n[e],g=m.readability.contentScore*(1-this._getLinkDensity(m)),m.readability.contentScore=g,this.log("Candidate:",m,"with score "+g),k=0;k<this._nbTopCandidates;k++)if(l=h[k],!l||g>l.readability.contentScore){h.splice(k,0,m);h.length>this._nbTopCandidates&&h.pop();break}e=h[0]||null;f=!1;if(null===e||"BODY"===e.tagName){e=c.createElement("DIV");
for(f=!0;a.firstChild;)this.log("Moving child out:",a.firstChild),e.appendChild(a.firstChild);a.appendChild(e);this._initializeNode(e)}else if(e){m=[];for(g=1;g<h.length;g++).75<=h[g].readability.contentScore/e.readability.contentScore&&m.push(this._getNodeAncestors(h[g]));if(3<=m.length)for(h=e.parentNode;"BODY"!==h.tagName;){for(k=g=0;k<m.length&&3>g;k++)g+=Number(m[k].includes(h));if(3<=g){e=h;break}h=h.parentNode}e.readability||this._initializeNode(e);h=e.parentNode;m=e.readability.contentScore;
for(g=m/3;"BODY"!==h.tagName;){if(h.readability){k=h.readability.contentScore;if(k<g)break;if(k>m){e=h;break}m=h.readability.contentScore}h=h.parentNode}for(h=e.parentNode;"BODY"!=h.tagName&&1==h.children.length;)e=h,h=e.parentNode;e.readability||this._initializeNode(e)}m=c.createElement("DIV");b&&(m.id="readability-content");g=Math.max(10,.2*e.readability.contentScore);h=e.parentNode;k=h.children;l=0;for(var q=k.length;l<q;l++){var p=k[l],r=!1;this.log("Looking at sibling node:",p,p.readability?
"with score "+p.readability.contentScore:"");this.log("Sibling has score",p.readability?p.readability.contentScore:"Unknown");if(p===e)r=!0;else{var u=0;p.className===e.className&&""!==e.className&&(u+=.2*e.readability.contentScore);if(p.readability&&p.readability.contentScore+u>=g)r=!0;else if("P"===p.nodeName){u=this._getLinkDensity(p);var w=this._getInnerText(p),A=w.length;80<A&&.25>u?r=!0:80>A&&0<A&&0===u&&-1!==w.search(/\.( |$)/)&&(r=!0)}}r&&(this.log("Appending node:",p),-1===this.ALTER_TO_DIV_EXCEPTIONS.indexOf(p.nodeName)&&
(this.log("Altering sibling:",p,"to div."),p=this._setNodeTag(p,"DIV")),m.appendChild(p),k=h.children,--l,--q)}this._debug&&this.log("Article content pre-prep: "+m.innerHTML);this._prepArticle(m);this._debug&&this.log("Article content post-prep: "+m.innerHTML);if(f)e.id="readability-page-1",e.className="page";else{f=c.createElement("DIV");f.id="readability-page-1";for(f.className="page";m.firstChild;)f.appendChild(m.firstChild);m.appendChild(f)}this._debug&&this.log("Article content after paging: "+
m.innerHTML);f=!0;g=this._getInnerText(m,!0).length;if(g<this._charThreshold)if(f=!1,a.innerHTML=d,this._flagIsActive(this.FLAG_STRIP_UNLIKELYS))this._removeFlag(this.FLAG_STRIP_UNLIKELYS),this._attempts.push({articleContent:m,textLength:g});else if(this._flagIsActive(this.FLAG_WEIGHT_CLASSES))this._removeFlag(this.FLAG_WEIGHT_CLASSES),this._attempts.push({articleContent:m,textLength:g});else if(this._flagIsActive(this.FLAG_CLEAN_CONDITIONALLY))this._removeFlag(this.FLAG_CLEAN_CONDITIONALLY),this._attempts.push({articleContent:m,
textLength:g});else{this._attempts.push({articleContent:m,textLength:g});this._attempts.sort(function(t,x){return x.textLength-t.textLength});if(!this._attempts[0].textLength)return null;m=this._attempts[0].articleContent;f=!0}if(f)return a=[h,e].concat(this._getNodeAncestors(h)),this._someNode(a,function(t){return t.tagName?(t=t.getAttribute("dir"))?(this._articleDir=t,!0):!1:!1}),m}},_isValidByline:function(a){return"string"==typeof a||a instanceof String?(a=a.trim(),0<a.length&&100>a.length):!1},
_unescapeHtmlEntities:function(a){if(!a)return a;var c=this.HTML_ESCAPE_MAP;return a.replace(/&(quot|amp|apos|lt|gt);/g,function(b,d){return c[d]}).replace(/&#(?:x([0-9a-z]{1,4})|([0-9]{1,4}));/gi,function(b,d,e){b=parseInt(d||e,d?16:10);return String.fromCharCode(b)})},_getJSONLD:function(a){a=this._getAllNodesWithTag(a,["script"]);if(a=this._findNode(a,function(d){return"application/ld+json"===d.getAttribute("type")}))try{var c=a.textContent.replace(/^\s*<!\[CDATA\[|\]\]>\s*$/g,""),b=JSON.parse(c);
c={};if(!b["@context"]||!b["@context"].match(/^https?:\/\/schema\.org$/))return c;!b["@type"]&&Array.isArray(b["@graph"])&&(b=b["@graph"].find(function(d){return(d["@type"]||"").match(this.REGEXPS.jsonLdArticleTypes)}));if(!b||!b["@type"]||!b["@type"].match(this.REGEXPS.jsonLdArticleTypes))return c;"string"===typeof b.name?c.title=b.name.trim():"string"===typeof b.headline&&(c.title=b.headline.trim());b.author&&("string"===typeof b.author.name?c.byline=b.author.name.trim():Array.isArray(b.author)&&
b.author[0]&&"string"===typeof b.author[0].name&&(c.byline=b.author.filter(function(d){return d&&"string"===typeof d.name}).map(function(d){return d.name.trim()}).join(", ")));"string"===typeof b.description&&(c.excerpt=b.description.trim());b.publisher&&"string"===typeof b.publisher.name&&(c.siteName=b.publisher.name.trim());return c}catch(d){this.log(d.message)}return{}},_getArticleMetadata:function(a){var c={},b={},d=this._doc.getElementsByTagName("meta"),e=/\s*(dc|dcterm|og|twitter)\s*:\s*(author|creator|description|title|site_name)\s*/gi,
h=/^\s*(?:(dc|dcterm|og|twitter|weibo:(article|webpage))\s*[\.:]\s*)?(author|creator|description|title|site_name)\s*$/i;this._forEachNode(d,function(f){var m=f.getAttribute("name"),g=f.getAttribute("property");if(f=f.getAttribute("content")){var k=null;g&&(k=g.match(e))&&(g=k[0].toLowerCase().replace(/\s/g,""),b[g]=f.trim());!k&&m&&h.test(m)&&f&&(g=m.toLowerCase().replace(/\s/g,"").replace(/\./g,":"),b[g]=f.trim())}});c.title=a.title||b["dc:title"]||b["dcterm:title"]||b["og:title"]||b["weibo:article:title"]||
b["weibo:webpage:title"]||b.title||b["twitter:title"];c.title||(c.title=this._getArticleTitle());c.byline=a.byline||b["dc:creator"]||b["dcterm:creator"]||b.author;c.excerpt=a.excerpt||b["dc:description"]||b["dcterm:description"]||b["og:description"]||b["weibo:article:description"]||b["weibo:webpage:description"]||b.description||b["twitter:description"];c.siteName=a.siteName||b["og:site_name"];c.title=this._unescapeHtmlEntities(c.title);c.byline=this._unescapeHtmlEntities(c.byline);c.excerpt=this._unescapeHtmlEntities(c.excerpt);
c.siteName=this._unescapeHtmlEntities(c.siteName);return c},_isSingleImage:function(a){return"IMG"===a.tagName?!0:1!==a.children.length||""!==a.textContent.trim()?!1:this._isSingleImage(a.children[0])},_unwrapNoscriptImages:function(a){var c=Array.from(a.getElementsByTagName("img"));this._forEachNode(c,function(b){for(var d=0;d<b.attributes.length;d++){var e=b.attributes[d];switch(e.name){case "src":case "srcset":case "data-src":case "data-srcset":return}if(/\.(jpg|jpeg|png|webp)/i.test(e.value))return}b.parentNode.removeChild(b)});
c=Array.from(a.getElementsByTagName("noscript"));this._forEachNode(c,function(b){var d=a.createElement("div");d.innerHTML=b.innerHTML;if(this._isSingleImage(d)){var e=b.previousElementSibling;if(e&&this._isSingleImage(e)){var h=e;"IMG"!==h.tagName&&(h=e.getElementsByTagName("img")[0]);for(var f=d.getElementsByTagName("img")[0],m=0;m<h.attributes.length;m++){var g=h.attributes[m];if(""!==g.value&&("src"===g.name||"srcset"===g.name||/\.(jpg|jpeg|png|webp)/i.test(g.value))&&f.getAttribute(g.name)!==
g.value){var k=g.name;f.hasAttribute(k)&&(k="data-old-"+k);f.setAttribute(k,g.value)}}b.parentNode.replaceChild(d.firstElementChild,e)}}})},_removeScripts:function(a){this._removeNodes(this._getAllNodesWithTag(a,["script"]),function(c){c.nodeValue="";c.removeAttribute("src");return!0});this._removeNodes(this._getAllNodesWithTag(a,["noscript"]))},_hasSingleTagInsideElement:function(a,c){return 1!=a.children.length||a.children[0].tagName!==c?!1:!this._someNode(a.childNodes,function(b){return b.nodeType===
this.TEXT_NODE&&this.REGEXPS.hasContent.test(b.textContent)})},_isElementWithoutContent:function(a){return a.nodeType===this.ELEMENT_NODE&&0==a.textContent.trim().length&&(0==a.children.length||a.children.length==a.getElementsByTagName("br").length+a.getElementsByTagName("hr").length)},_hasChildBlockElement:function(a){return this._someNode(a.childNodes,function(c){return this.DIV_TO_P_ELEMS.has(c.tagName)||this._hasChildBlockElement(c)})},_isPhrasingContent:function(a){return a.nodeType===this.TEXT_NODE||
-1!==this.PHRASING_ELEMS.indexOf(a.tagName)||("A"===a.tagName||"DEL"===a.tagName||"INS"===a.tagName)&&this._everyNode(a.childNodes,this._isPhrasingContent)},_isWhitespace:function(a){return a.nodeType===this.TEXT_NODE&&0===a.textContent.trim().length||a.nodeType===this.ELEMENT_NODE&&"BR"===a.tagName},_getInnerText:function(a,c){c="undefined"===typeof c?!0:c;a=a.textContent.trim();return c?a.replace(this.REGEXPS.normalize," "):a},_getCharCount:function(a,c){c=c||",";return this._getInnerText(a).split(c).length-
1},_cleanStyles:function(a){if(a&&"svg"!==a.tagName.toLowerCase()){for(var c=0;c<this.PRESENTATIONAL_ATTRIBUTES.length;c++)a.removeAttribute(this.PRESENTATIONAL_ATTRIBUTES[c]);-1!==this.DEPRECATED_SIZE_ATTRIBUTE_ELEMS.indexOf(a.tagName)&&(a.removeAttribute("width"),a.removeAttribute("height"));for(a=a.firstElementChild;null!==a;)this._cleanStyles(a),a=a.nextElementSibling}},_getLinkDensity:function(a){var c=this._getInnerText(a).length;if(0===c)return 0;var b=0;this._forEachNode(a.getElementsByTagName("a"),
function(d){var e=d.getAttribute("href");e=e&&this.REGEXPS.hashUrl.test(e)?.3:1;b+=this._getInnerText(d).length*e});return b/c},_getClassWeight:function(a){if(!this._flagIsActive(this.FLAG_WEIGHT_CLASSES))return 0;var c=0;"string"===typeof a.className&&""!==a.className&&(this.REGEXPS.negative.test(a.className)&&(c-=25),this.REGEXPS.positive.test(a.className)&&(c+=25));"string"===typeof a.id&&""!==a.id&&(this.REGEXPS.negative.test(a.id)&&(c-=25),this.REGEXPS.positive.test(a.id)&&(c+=25));return c},
_clean:function(a,c){var b=-1!==["object","embed","iframe"].indexOf(c);this._removeNodes(this._getAllNodesWithTag(a,[c]),function(d){if(b){for(var e=0;e<d.attributes.length;e++)if(this.REGEXPS.videos.test(d.attributes[e].value))return!1;if("object"===d.tagName&&this.REGEXPS.videos.test(d.innerHTML))return!1}return!0})},_hasAncestorTag:function(a,c,b,d){b=b||3;c=c.toUpperCase();for(var e=0;a.parentNode&&!(0<b&&e>b);){if(a.parentNode.tagName===c&&(!d||d(a.parentNode)))return!0;a=a.parentNode;e++}return!1},
_getRowAndColumnCount:function(a){var c=0,b=0;a=a.getElementsByTagName("tr");for(var d=0;d<a.length;d++){var e=a[d].getAttribute("rowspan")||0;e&&(e=parseInt(e,10));c+=e||1;e=0;for(var h=a[d].getElementsByTagName("td"),f=0;f<h.length;f++){var m=h[f].getAttribute("colspan")||0;m&&(m=parseInt(m,10));e+=m||1}b=Math.max(b,e)}return{rows:c,columns:b}},_markDataTables:function(a){a=a.getElementsByTagName("table");for(var c=0;c<a.length;c++){var b=a[c];if("presentation"==b.getAttribute("role"))b._readabilityDataTable=
!1;else if("0"==b.getAttribute("datatable"))b._readabilityDataTable=!1;else if(b.getAttribute("summary"))b._readabilityDataTable=!0;else{var d=b.getElementsByTagName("caption")[0];d&&0<d.childNodes.length?b._readabilityDataTable=!0:["col","colgroup","tfoot","thead","th"].some(function(e){return!!b.getElementsByTagName(e)[0]})?(this.log("Data table because found data-y descendant"),b._readabilityDataTable=!0):b.getElementsByTagName("table")[0]?b._readabilityDataTable=!1:(d=this._getRowAndColumnCount(b),
b._readabilityDataTable=10<=d.rows||4<d.columns?!0:10<d.rows*d.columns)}}},_fixLazyImages:function(a){this._forEachNode(this._getAllNodesWithTag(a,["img","picture","figure"]),function(c){if(c.src&&this.REGEXPS.b64DataUrl.test(c.src)){if("image/svg+xml"===this.REGEXPS.b64DataUrl.exec(c.src)[1])return;for(var b=!1,d=0;d<c.attributes.length;d++){var e=c.attributes[d];if("src"!==e.name&&/\.(jpg|jpeg|png|webp)/i.test(e.value)){b=!0;break}}b&&(e=c.src.search(/base64\s*/i)+7,133>c.src.length-e&&c.removeAttribute("src"))}if(!(c.src||
c.srcset&&"null"!=c.srcset)||-1!==c.className.toLowerCase().indexOf("lazy"))for(b=0;b<c.attributes.length;b++)if(e=c.attributes[b],"src"!==e.name&&"srcset"!==e.name&&"alt"!==e.name&&(d=null,/\.(jpg|jpeg|png|webp)\s+\d/.test(e.value)?d="srcset":/^\s*\S+\.(jpg|jpeg|png|webp)\S*\s*$/.test(e.value)&&(d="src"),d))if("IMG"===c.tagName||"PICTURE"===c.tagName)c.setAttribute(d,e.value);else if("FIGURE"===c.tagName&&!this._getAllNodesWithTag(c,["img","picture"]).length){var h=this._doc.createElement("img");
h.setAttribute(d,e.value);c.appendChild(h)}})},_getTextDensity:function(a,c){var b=this,d=this._getInnerText(a,!0).length;if(0===d)return 0;var e=0;a=this._getAllNodesWithTag(a,c);this._forEachNode(a,function(h){return e+=b._getInnerText(h,!0).length});return e/d},_cleanConditionally:function(a,c){this._flagIsActive(this.FLAG_CLEAN_CONDITIONALLY)&&this._removeNodes(this._getAllNodesWithTag(a,[c]),function(b){var d=this,e="ul"===c||"ol"===c;if(!e){var h=0;e=this._getAllNodesWithTag(b,["ul","ol"]);
this._forEachNode(e,function(w){return h+=d._getInnerText(w).length});e=.9<h/this._getInnerText(b).length}if("table"===c&&b._readabilityDataTable||this._hasAncestorTag(b,"table",-1,function(w){return w._readabilityDataTable})||this._hasAncestorTag(b,"code"))return!1;var f=this._getClassWeight(b);this.log("Cleaning Conditionally",b);if(0>f+0)return!0;if(10>this._getCharCount(b,",")){for(var m=b.getElementsByTagName("p").length,g=b.getElementsByTagName("img").length,k=b.getElementsByTagName("li").length-
100,l=b.getElementsByTagName("input").length,n=this._getTextDensity(b,"h1 h2 h3 h4 h5 h6".split(" ")),q=0,p=this._getAllNodesWithTag(b,["object","embed","iframe"]),r=0;r<p.length;r++){for(var u=0;u<p[r].attributes.length;u++)if(this.REGEXPS.videos.test(p[r].attributes[u].value))return!1;if("object"===p[r].tagName&&this.REGEXPS.videos.test(p[r].innerHTML))return!1;q++}p=this._getLinkDensity(b);r=this._getInnerText(b).length;return 1<g&&.5>m/g&&!this._hasAncestorTag(b,"figure")||!e&&k>m||l>Math.floor(m/
3)||!e&&.9>n&&25>r&&(0===g||2<g)&&!this._hasAncestorTag(b,"figure")||!e&&25>f&&.2<p||25<=f&&.5<p||1===q&&75>r||1<q}return!1})},_cleanMatchedNodes:function(a,c){var b=this._getNextNode(a,!0);for(a=this._getNextNode(a);a&&a!=b;)a=c.call(this,a,a.className+" "+a.id)?this._removeAndGetNext(a):this._getNextNode(a)},_cleanHeaders:function(a){a=this._getAllNodesWithTag(a,["h1","h2"]);this._removeNodes(a,function(c){var b=0>this._getClassWeight(c);b&&this.log("Removing header with low class weight:",c);return b})},
_headerDuplicatesTitle:function(a){if("H1"!=a.tagName&&"H2"!=a.tagName)return!1;a=this._getInnerText(a,!1);this.log("Evaluating similarity of header:",a,this._articleTitle);return.75<this._textSimilarity(this._articleTitle,a)},_flagIsActive:function(a){return 0<(this._flags&a)},_removeFlag:function(a){this._flags&=~a},_isProbablyVisible:function(a){return(!a.style||"none"!=a.style.display)&&!a.hasAttribute("hidden")&&(!a.hasAttribute("aria-hidden")||"true"!=a.getAttribute("aria-hidden")||a.className&&
a.className.indexOf&&-1!==a.className.indexOf("fallback-image"))},parse:function(){if(0<this._maxElemsToParse){var a=this._doc.getElementsByTagName("*").length;if(a>this._maxElemsToParse)throw Error("Aborting parsing document; "+a+" elements found");}this._unwrapNoscriptImages(this._doc);a=this._disableJSONLD?{}:this._getJSONLD(this._doc);this._removeScripts(this._doc);this._prepDocument();a=this._getArticleMetadata(a);this._articleTitle=a.title;var c=this._grabArticle();if(!c)return null;this.log("Grabbed: "+
c.innerHTML);this._postProcessContent(c);if(!a.excerpt){var b=c.getElementsByTagName("p");0<b.length&&(a.excerpt=b[0].textContent.trim())}b=c.textContent;return{title:this._articleTitle,byline:a.byline||this._articleByline,dir:this._articleDir,content:this._serializer(c),textContent:b,length:b.length,excerpt:a.excerpt,siteName:a.siteName||this._articleSiteName}}};"object"===typeof module&&(module.exports=Readability);
