/*
 Copyright (c) 2010 Arc90 Inc
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
       http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
//Based on Arc90's readability.js (1.7.1) available at: http://code.google.com/p/arc90labs-readability

function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function q(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var r="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this);function t(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&r(c,a,{configurable:!0,writable:!0,value:b})}}
t("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(f){return f};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var h=0;!(g=b.next()).done;)e.push(c.call(d,g.value,h++))}else for(g=b.length,h=0;h<g;h++)e.push(c.call(d,b[h],h));return e}});
t("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,g){this.h=e;r(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.h};var d=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&r(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function x(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
t("WeakMap",function(a){function b(l){this.h=(f+=Math.random()+1).toString();if(l){l=q(l);for(var k;!(k=l.next()).done;)k=k.value,this.set(k[0],k[1])}}function c(){}function d(l){var k=typeof l;return"object"===k&&null!==l||"function"===k}function e(l){if(!x(l,h)){var k=new c;r(l,h,{value:k})}}function g(l){var k=Object[l];k&&(Object[l]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return k(m)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),k=Object.seal({}),
m=new a([[l,2],[k,3]]);if(2!=m.get(l)||3!=m.get(k))return!1;m.delete(l);m.set(k,4);return!m.has(l)&&4==m.get(k)}catch(p){return!1}}())return a;var h="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var f=0;b.prototype.set=function(l,k){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!x(l,h))throw Error("WeakMap key fail: "+l);l[h][this.h]=k;return this};b.prototype.get=function(l){return d(l)&&x(l,h)?l[h][this.h]:void 0};b.prototype.has=function(l){return d(l)&&x(l,
h)&&x(l[h],this.h)};b.prototype.delete=function(l){return d(l)&&x(l,h)&&x(l[h],this.h)?delete l[h][this.h]:!1};return b});
t("Map",function(a){function b(){var f={};return f.u=f.next=f.head=f}function c(f,l){var k=f.h;return da(function(){if(k){for(;k.head!=f.h;)k=k.u;for(;k.next!=k.head;)return k=k.next,{done:!1,value:l(k)};k=null}return{done:!0,value:void 0}})}function d(f,l){var k=l&&typeof l;"object"==k||"function"==k?g.has(l)?k=g.get(l):(k=""+ ++h,g.set(l,k)):k="p_"+l;var m=f.G[k];if(m&&x(f.G,k))for(f=0;f<m.length;f++){var p=m[f];if(l!==l&&p.key!==p.key||l===p.key)return{id:k,list:m,index:f,m:p}}return{id:k,list:m,
index:-1,m:void 0}}function e(f){this.G={};this.h=b();this.size=0;if(f){f=q(f);for(var l;!(l=f.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),l=new a(q([[f,"s"]]));if("s"!=l.get(f)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var k=l.entries(),m=k.next();if(m.done||m.value[0]!=f||"s"!=m.value[1])return!1;m=k.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!k.next().done?!1:!0}catch(p){return!1}}())return a;var g=new WeakMap;e.prototype.set=function(f,l){f=0===f?0:f;var k=d(this,f);k.list||(k.list=this.G[k.id]=[]);k.m?k.m.value=l:(k.m={next:this.h,u:this.h.u,head:this.h,key:f,value:l},k.list.push(k.m),this.h.u.next=k.m,this.h.u=k.m,this.size++);return this};e.prototype.delete=function(f){f=d(this,f);return f.m&&f.list?(f.list.splice(f.index,1),f.list.length||delete this.G[f.id],f.m.u.next=f.m.next,f.m.next.u=f.m.u,f.m.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.G={};this.h=this.h.u=b();this.size=0};e.prototype.has=function(f){return!!d(this,f).m};e.prototype.get=function(f){return(f=d(this,f).m)&&f.value};e.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};e.prototype.keys=function(){return c(this,function(f){return f.key})};e.prototype.values=function(){return c(this,function(f){return f.value})};e.prototype.forEach=function(f,l){for(var k=this.entries(),m;!(m=k.next()).done;)m=m.value,
f.call(l,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var h=0;return e});
t("Set",function(a){function b(c){this.h=new Map;if(c){c=q(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.h.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(q([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),g=e.next();if(g.done||g.value[0]!=c||g.value[1]!=c)return!1;g=e.next();return g.done||g.value[0]==c||4!=g.value[0].x||
g.value[1]!=g.value[0]?!1:e.next().done}catch(h){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.h.set(c,c);this.size=this.h.size;return this};b.prototype.delete=function(c){c=this.h.delete(c);this.size=this.h.size;return c};b.prototype.clear=function(){this.h.clear();this.size=0};b.prototype.has=function(c){return this.h.has(c)};b.prototype.entries=function(){return this.h.entries()};b.prototype.values=function(){return this.h.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.h.forEach(function(g){return c.call(d,g,g,e)})};return b});t("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,g=0;g<e;g++){var h=d[g];if(b.call(c,h,g,d)){b=h;break a}}b=void 0}return b}});t("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
t("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});function ea(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
t("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==ea(this,b,"includes").indexOf(b,c||0)}});t("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=ea(this,b,"startsWith"),e=d.length,g=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<g&&c<e;)if(d[c++]!=b[h++])return!1;return h>=g}});
function fa(a,b,c){if(b&&b.documentElement)a=b,b=c;else if(!a||!a.documentElement)throw Error("First argument to Readability constructor should be a document object.");b=b||{};this.l=a;this.P=this.l.firstChild.Ca;this.ma=this.T=this.O=this.F=null;this.B=[];this.K=!!b.debug;this.U=b.Ia||this.ea;this.V=b.Ja||this.fa;this.na=b.Da||this.R;this.oa=this.da.concat(b.Ea||[]);this.sa=!!b.Ha;this.ta=b.Na||function(e){return e.innerHTML};this.qa=!!b.Fa;this.o=this.I|this.J|this.H;if(this.K){var d=function(e){if(e.nodeType==
e.TEXT_NODE)return e.nodeName+' ("'+e.textContent+'")';var g=Array.from(e.attributes||[],function(h){return h.name+'="'+h.value+'"'}).join(" ");return"<"+e.localName+" "+g+">"};this.log=function(){var e=this;if("undefined"!==typeof dump){var g=Array.prototype.map.call(arguments,function(h){return h&&h.nodeName?d(h):h}).join(" ");dump("Reader: (Readability) "+g+"\n")}else"undefined"!==typeof console&&(g=Array.from(arguments,function(h){return h&&h.nodeType==e.ELEMENT_NODE?d(h):h}),g.unshift("Reader: (Readability)"),
console.log.apply(console,g))}}else this.log=function(){}}
function ha(a,b){function c(h){if(d==e&&"#"==h.charAt(0))return h;try{return(new URL(h,d)).href}catch(f){}return h}var d=a.l.baseURI,e=a.l.documentURI,g=y(b,["a"]);z(a,g,function(h){var f=h.getAttribute("href");if(f)if(0===f.indexOf("javascript:"))if(1===h.childNodes.length&&h.childNodes[0].nodeType===this.TEXT_NODE)h.parentNode.replaceChild(this.l.createTextNode(h.textContent),h);else{for(f=this.l.createElement("span");0<h.childNodes.length;)f.appendChild(h.childNodes[0]);h.parentNode.replaceChild(f,
h)}else h.setAttribute("href",c(f))});b=y(b,"img picture figure video audio source".split(" "));z(a,b,function(h){var f=h.getAttribute("src"),l=h.getAttribute("poster"),k=h.getAttribute("srcset");f&&h.setAttribute("src",c(f));l&&h.setAttribute("poster",c(l));k&&(f=k.replace(this.i.za,function(m,p,C,G){return c(p)+(C||"")+G}),h.setAttribute("srcset",f))})}
function ia(a,b){var c=a.oa,d=(b.getAttribute("class")||"").split(/\s+/).filter(function(e){return-1!=c.indexOf(e)}).join(" ");d?b.setAttribute("class",d):b.removeAttribute("class");for(b=b.firstElementChild;b;b=b.nextElementSibling)ia(a,b)}function A(a,b,c){if(a.P&&b.ra)throw Error("Do not pass live node lists to _removeNodes");for(var d=b.length-1;0<=d;d--){var e=b[d],g=e.parentNode;g&&(!c||c.call(a,e,d,b))&&g.removeChild(e)}}
function D(a,b,c){a.log("_setNodeTag",b,c);if(a.P)return b.localName=c.toLowerCase(),b.tagName=c.toUpperCase(),b;for(a=b.ownerDocument.createElement(c);b.firstChild;)a.appendChild(b.firstChild);b.parentNode.replaceChild(a,b);b.g&&(a.g=b.g);for(c=0;c<b.attributes.length;c++)try{a.setAttribute(b.attributes[c].name,b.attributes[c].value)}catch(d){}return a}
function ja(a,b,c){if(a.P&&b.ra)throw Error("Do not pass live node lists to _replaceNodeTags");b=q(b);for(var d=b.next();!d.done;d=b.next())D(a,d.value,c)}function z(a,b,c){Array.prototype.forEach.call(b,c,a)}function ka(a,b,c){return Array.prototype.find.call(b,c,a)}function F(a,b,c){return Array.prototype.some.call(b,c,a)}
function y(a,b){return a.querySelectorAll?a.querySelectorAll(b.join(",")):[].concat.apply([],b.map(function(c){c=a.getElementsByTagName(c);return Array.isArray(c)?c:Array.from(c)}))}function la(a,b){return b.nodeType===a.ELEMENT_NODE&&0==b.textContent.trim().length&&(0==b.children.length||b.children.length==b.getElementsByTagName("br").length+b.getElementsByTagName("hr").length)}function H(a){var b=I(a,!0);a.parentNode.removeChild(a);return b}
function J(a,b,c){return 1!=b.children.length||b.children[0].tagName!==c?!1:!F(a,b.childNodes,function(d){return d.nodeType===this.TEXT_NODE&&this.i.ua.test(d.textContent)})}function I(a,b){if(!b&&a.firstElementChild)return a.firstElementChild;if(a.nextElementSibling)return a.nextElementSibling;do a=a.parentNode;while(a&&!a.nextElementSibling);return a&&a.nextElementSibling}function L(a,b,c){b=b.textContent.trim();return"undefined"===typeof c||c?b.replace(a.i.normalize," "):b}
function ma(a){function b(f){return f.split(/\s+/).length}var c=a.l,d="",e="";try{d=e=c.title.trim(),"string"!==typeof d&&(d=e=L(a,c.getElementsByTagName("title")[0]))}catch(f){}var g=!1;if(/ [\|\-\\\/>\u00bb] /.test(d))g=/ [\\\/>\u00bb] /.test(d),d=e.replace(/(.*)[\|\-\\\/>\u00bb] .*/gi,"$1"),3>b(d)&&(d=e.replace(/[^\|\-\\\/>\u00bb]*[\|\-\\\/>\u00bb](.*)/gi,"$1"));else if(-1!==d.indexOf(": ")){c=a.pa(c.getElementsByTagName("h1"),c.getElementsByTagName("h2"));var h=d.trim();F(a,c,function(f){return f.textContent.trim()===
h})||(d=e.substring(e.lastIndexOf(":")+1),3>b(d)?d=e.substring(e.indexOf(":")+1):5<b(e.substr(0,e.indexOf(":")))&&(d=e))}else if(150<d.length||15>d.length)c=c.getElementsByTagName("h1"),1===c.length&&(d=L(a,c[0]));d=d.trim().replace(a.i.normalize," ");a=b(d);4>=a&&(!g||a!=b(e.replace(/[\|\-\\\/>\u00bb]+/g,""))-1)&&(d=e);return d}
function na(a,b){z(a,y(b,["br"]),function(c){for(var d=c.nextSibling,e=!1;(d=M(this,d))&&"BR"==d.tagName;){e=!0;var g=d.nextSibling;d.parentNode.removeChild(d);d=g}if(e){e=this.l.createElement("p");c.parentNode.replaceChild(e,c);for(d=e.nextSibling;d&&("BR"!=d.tagName||!(c=M(this,d.nextSibling))||"BR"!=c.tagName)&&this.L(d);)c=d.nextSibling,e.appendChild(d),d=c;for(;e.lastChild&&O(this,e.lastChild);)e.removeChild(e.lastChild);"P"===e.parentNode.tagName&&D(this,e.parentNode,"DIV")}})}
function M(a,b){for(;b&&b.nodeType!=a.ELEMENT_NODE&&a.i.Ba.test(b.textContent);)b=b.nextSibling;return b}function O(a,b){return b.nodeType===a.TEXT_NODE&&0===b.textContent.trim().length||b.nodeType===a.ELEMENT_NODE&&"BR"===b.tagName}function oa(a,b){if(b&&"svg"!==b.tagName.toLowerCase()){for(var c=0;c<a.S.length;c++)b.removeAttribute(a.S[c]);-1!==a.ha.indexOf(b.tagName)&&(b.removeAttribute("width"),b.removeAttribute("height"));for(b=b.firstElementChild;null!==b;)oa(a,b),b=b.nextElementSibling}}
function pa(a,b){b=b.getElementsByTagName("table");for(var c=0;c<b.length;c++){var d=b[c];if("presentation"==d.getAttribute("role"))d.v=!1;else if("0"==d.getAttribute("datatable"))d.v=!1;else if(d.getAttribute("summary"))d.v=!0;else{var e=d.getElementsByTagName("caption")[0];e&&0<e.childNodes.length?d.v=!0:["col","colgroup","tfoot","thead","th"].some(function(g){return!!d.getElementsByTagName(g)[0]})?(a.log("Data table because found data-y descendant"),d.v=!0):d.getElementsByTagName("table")[0]?d.v=
!1:(e=qa(d),d.v=10<=e.rows||4<e.X?!0:10<e.rows*e.X)}}}
function ra(a,b){z(a,y(b,["img","picture","figure"]),function(c){if(c.src&&this.i.W.test(c.src)){if("image/svg+xml"===this.i.W.exec(c.src)[1])return;for(var d=!1,e=0;e<c.attributes.length;e++){var g=c.attributes[e];if("src"!==g.name&&/\.(jpg|jpeg|png|webp)/i.test(g.value)){d=!0;break}}d&&(g=c.src.search(/base64\s*/i)+7,133>c.src.length-g&&c.removeAttribute("src"))}if(!(c.src||c.srcset&&"null"!=c.srcset)||-1!==c.className.toLowerCase().indexOf("lazy"))for(d=0;d<c.attributes.length;d++)if(g=c.attributes[d],
"src"!==g.name&&"srcset"!==g.name&&(e=null,/\.(jpg|jpeg|png|webp)\s+\d/.test(g.value)?e="srcset":/^\s*\S+\.(jpg|jpeg|png|webp)\S*\s*$/.test(g.value)&&(e="src"),e))if("IMG"===c.tagName||"PICTURE"===c.tagName)c.setAttribute(e,g.value);else if("FIGURE"===c.tagName&&!y(c,["img","picture"]).length){var h=this.l.createElement("img");h.setAttribute(e,g.value);c.appendChild(h)}})}
function P(a,b,c){0<(a.o&a.H)&&A(a,y(b,[c]),function(d){function e(E){return E.v}var g=this,h="ul"===c||"ol"===c;if(!h){var f=0;h=y(d,["ul","ol"]);z(this,h,function(E){return f+=L(g,E).length});h=.9<f/L(this,d).length}if("table"===c&&d.v||Q(d,"table",-1,e)||Q(d,"code"))return!1;var l=R(this,d);this.log("Cleaning Conditionally",d);if(0>l+0)return!0;if(10>sa(this,d)){for(var k=d.getElementsByTagName("p").length,m=d.getElementsByTagName("img").length,p=d.getElementsByTagName("li").length-100,C=d.getElementsByTagName("input").length,
G=ta(this,d),n=0,v=y(d,["object","embed","iframe"]),u=0;u<v.length;u++){for(var K=0;K<v[u].attributes.length;K++)if(this.i.N.test(v[u].attributes[K].value))return!1;if("object"===v[u].tagName&&this.i.N.test(v[u].innerHTML))return!1;n++}v=T(this,d);u=L(this,d).length;return 1<m&&.5>k/m&&!Q(d,"figure")||!h&&p>k||C>Math.floor(k/3)||!h&&.9>G&&25>u&&(0===m||2<m)&&!Q(d,"figure")||!h&&25>l&&.2<v||25<=l&&.5<v||1===n&&75>u||1<n}return!1})}
function U(a,b,c){var d=-1!==["object","embed","iframe"].indexOf(c);A(a,y(b,[c]),function(e){if(d){for(var g=0;g<e.attributes.length;g++)if(this.i.N.test(e.attributes[g].value))return!1;if("object"===e.tagName&&this.i.N.test(e.innerHTML))return!1}return!0})}function ua(a,b,c){var d=I(b,!0);for(b=I(b);b&&b!=d;)b=c.call(a,b,b.className+" "+b.id)?H(b):I(b)}function va(a,b){b=y(b,["h1","h2"]);A(a,b,function(c){var d=0>R(this,c);d&&this.log("Removing header with low class weight:",c);return d})}
function wa(a,b){oa(a,b);pa(a,b);ra(a,b);P(a,b,"form");P(a,b,"fieldset");U(a,b,"object");U(a,b,"embed");U(a,b,"footer");U(a,b,"link");U(a,b,"aside");var c=a.R;z(a,b.children,function(d){ua(this,d,function(e,g){return this.i.ya.test(g)&&e.textContent.length<c})});U(a,b,"iframe");U(a,b,"input");U(a,b,"textarea");U(a,b,"select");U(a,b,"button");va(a,b);P(a,b,"table");P(a,b,"ul");P(a,b,"div");ja(a,y(b,["h1"]),"h2");A(a,y(b,["p"]),function(d){return 0===d.getElementsByTagName("img").length+d.getElementsByTagName("embed").length+
d.getElementsByTagName("object").length+d.getElementsByTagName("iframe").length&&!L(this,d,!1)});z(a,y(b,["br"]),function(d){var e=M(this,d.nextSibling);e&&"P"==e.tagName&&d.parentNode.removeChild(d)});z(a,y(b,["table"]),function(d){var e=J(this,d,"TBODY")?d.firstElementChild:d;J(this,e,"TR")&&(e=e.firstElementChild,J(this,e,"TD")&&(e=e.firstElementChild,e=D(this,e,Array.prototype.every.call(e.childNodes,this.L,this)?"P":"DIV"),d.parentNode.replaceChild(e,d)))})}
function R(a,b){if(!(0<(a.o&a.J)))return 0;var c=0;"string"===typeof b.className&&""!==b.className&&(a.i.Z.test(b.className)&&(c-=25),a.i.$.test(b.className)&&(c+=25));"string"===typeof b.id&&""!==b.id&&(a.i.Z.test(b.id)&&(c-=25),a.i.$.test(b.id)&&(c+=25));return c}
function V(a,b){b.g={contentScore:0};switch(b.tagName){case "DIV":b.g.j+=5;break;case "PRE":case "TD":case "BLOCKQUOTE":b.g.j+=3;break;case "ADDRESS":case "OL":case "UL":case "DL":case "DD":case "DT":case "LI":case "FORM":b.g.j-=3;break;case "H1":case "H2":case "H3":case "H4":case "H5":case "H6":case "TH":b.g.j-=5}b.g.j+=R(a,b)}
function xa(a,b,c){var d=b.toLowerCase().split(a.i.ba).filter(Boolean);a=c.toLowerCase().split(a.i.ba).filter(Boolean);return d.length&&a.length?1-a.filter(function(e){return!d.includes(e)}).join(" ").length/a.join(" ").length:0}
function ya(a,b,c){if(a.O)return!1;if(void 0!==b.getAttribute)var d=b.getAttribute("rel"),e=b.getAttribute("itemprop");if(c="author"===d||e&&-1!==e.indexOf("author")||a.i.s.test(c))c=b.textContent,"string"==typeof c||c instanceof String?(c=c.trim(),c=0<c.length&&100>c.length):c=!1;return c?(a.O=b.textContent.trim(),!0):!1}function W(a,b){b=b||0;for(var c=0,d=[];a.parentNode;){d.push(a.parentNode);if(b&&++c===b)break;a=a.parentNode}return d}
function za(a){return(!a.style||"none"!=a.style.display)&&!a.hasAttribute("hidden")&&(!a.hasAttribute("aria-hidden")||"true"!=a.getAttribute("aria-hidden")||a.className&&a.className.indexOf&&-1!==a.className.indexOf("fallback-image"))}function Aa(a,b){if("H1"!=b.tagName&&"H2"!=b.tagName)return!1;b=L(a,b,!1);a.log("Evaluating similarity of header:",b,a.F);return.75<xa(a,a.F,b)}
function Q(a,b,c,d){c=c||3;b=b.toUpperCase();for(var e=0;a.parentNode&&!(0<c&&e>c);){if(a.parentNode.tagName===b&&(!d||d(a.parentNode)))return!0;a=a.parentNode;e++}return!1}function T(a,b){var c=L(a,b).length;if(0===c)return 0;var d=0;z(a,b.getElementsByTagName("a"),function(e){var g=e.getAttribute("href");g=g&&this.i.va.test(g)?.3:1;d+=L(this,e).length*g});return d/c}function Ba(a,b){return F(a,b.childNodes,function(c){return this.ia.has(c.tagName)||Ba(this,c)})}
function Ca(a){a.log("**** grabArticle ****");var b=a.l,c=null!==d;var d=d?d:a.l.body;if(!d)return a.log("No body found in document. Abort."),null;for(var e=d.innerHTML;;){a.log("Starting grabArticle loop");for(var g=0<(a.o&a.I),h=[],f=a.l.documentElement,l=!0;f;){var k=f.className+" "+f.id;if(za(f))if(ya(a,f,k))f=H(f);else if(l&&Aa(a,f))a.log("Removing header: ",f.textContent.trim(),a.F.trim()),l=!1,f=H(f);else{if(g){if(a.i.Aa.test(k)&&!a.i.xa.test(k)&&!Q(f,"table")&&!Q(f,"code")&&"BODY"!==f.tagName&&
"A"!==f.tagName){a.log("Removing unlikely candidate - "+k);f=H(f);continue}if(a.la.includes(f.getAttribute("role"))){a.log("Removing content with role "+f.getAttribute("role")+" - "+k);f=H(f);continue}}if("DIV"!==f.tagName&&"SECTION"!==f.tagName&&"HEADER"!==f.tagName&&"H1"!==f.tagName&&"H2"!==f.tagName&&"H3"!==f.tagName&&"H4"!==f.tagName&&"H5"!==f.tagName&&"H6"!==f.tagName||!la(a,f)){-1!==a.ga.indexOf(f.tagName)&&h.push(f);if("DIV"===f.tagName){k=null;for(var m=f.firstChild;m;){var p=m.nextSibling;
if(a.L(m))null!==k?k.appendChild(m):O(a,m)||(k=b.createElement("p"),f.replaceChild(k,m),k.appendChild(m));else if(null!==k){for(;k.lastChild&&O(a,k.lastChild);)k.removeChild(k.lastChild);k=null}m=p}J(a,f,"P")&&.25>T(a,f)?(k=f.children[0],f.parentNode.replaceChild(k,f),f=k,h.push(f)):Ba(a,f)||(f=D(a,f,"P"),h.push(f))}f=I(f)}else f=H(f)}else a.log("Removing hidden node - "+k),f=H(f)}var C=[];z(a,h,function(w){if(w.parentNode&&"undefined"!==typeof w.parentNode.tagName){var N=L(this,w);if(!(25>N.length)&&
(w=W(w,5),0!==w.length)){var S=0;S+=1;S+=N.split(",").length;S+=Math.min(Math.floor(N.length/100),3);z(this,w,function(B,Y){B.tagName&&B.parentNode&&"undefined"!==typeof B.parentNode.tagName&&("undefined"===typeof B.g&&(V(this,B),C.push(B)),B.g.j+=S/(0===Y?1:1===Y?2:3*Y))})}}});h=[];g=0;for(f=C.length;g<f;g+=1)for(l=C[g],k=l.g.j*(1-T(a,l)),l.g.j=k,a.log("Candidate:",l,"with score "+k),m=0;m<a.V;m++)if(p=h[m],!p||k>p.g.j){h.splice(m,0,l);h.length>a.V&&h.pop();break}g=h[0]||null;f=!1;if(null===g||"BODY"===
g.tagName){g=b.createElement("DIV");f=!0;for(h=d.childNodes;h.length;)a.log("Moving child out:",h[0]),g.appendChild(h[0]);d.appendChild(g);V(a,g)}else if(g){l=[];for(k=1;k<h.length;k++).75<=h[k].g.j/g.g.j&&l.push(W(h[k]));if(3<=l.length)for(h=g.parentNode;"BODY"!==h.tagName;){for(m=k=0;m<l.length&&3>k;m++)k+=Number(l[m].includes(h));if(3<=k){g=h;break}h=h.parentNode}g.g||V(a,g);h=g.parentNode;l=g.g.j;for(k=l/3;"BODY"!==h.tagName;){if(h.g){m=h.g.j;if(m<k)break;if(m>l){g=h;break}l=h.g.j}h=h.parentNode}for(h=
g.parentNode;"BODY"!=h.tagName&&1==h.children.length;)g=h,h=g.parentNode;g.g||V(a,g)}l=b.createElement("DIV");c&&(l.id="readability-content");k=Math.max(10,.2*g.g.j);h=g.parentNode;m=h.children;p=0;for(var G=m.length;p<G;p++){var n=m[p],v=!1;a.log("Looking at sibling node:",n,n.g?"with score "+n.g.j:"");a.log("Sibling has score",n.g?n.g.j:"Unknown");if(n===g)v=!0;else{var u=0;n.className===g.className&&""!==g.className&&(u+=.2*g.g.j);if(n.g&&n.g.j+u>=k)v=!0;else if("P"===n.nodeName){u=T(a,n);var K=
L(a,n),E=K.length;80<E&&.25>u?v=!0:80>E&&0<E&&0===u&&-1!==K.search(/\.( |$)/)&&(v=!0)}}v&&(a.log("Appending node:",n),-1===a.ca.indexOf(n.nodeName)&&(a.log("Altering sibling:",n,"to div."),n=D(a,n,"DIV")),l.appendChild(n),--p,--G)}a.K&&a.log("Article content pre-prep: "+l.innerHTML);wa(a,l);a.K&&a.log("Article content post-prep: "+l.innerHTML);if(f)g.id="readability-page-1",g.className="page";else{f=b.createElement("DIV");f.id="readability-page-1";f.className="page";for(k=l.childNodes;k.length;)f.appendChild(k[0]);
l.appendChild(f)}a.K&&a.log("Article content after paging: "+l.innerHTML);f=!0;k=L(a,l,!0).length;if(k<a.na)if(f=!1,d.innerHTML=e,0<(a.o&a.I))a.o=a.o&~a.I,a.B.push({M:l,textLength:k});else if(0<(a.o&a.J))a.o=a.o&~a.J,a.B.push({M:l,textLength:k});else if(0<(a.o&a.H))a.o=a.o&~a.H,a.B.push({M:l,textLength:k});else{a.B.push({M:l,textLength:k});a.B.sort(function(w,N){return N.textLength-w.textLength});if(!a.B[0].textLength)return null;l=a.B[0].M;f=!0}if(f)return d=[h,g].concat(W(h)),F(a,d,function(w){return w.tagName?
(w=w.getAttribute("dir"))?(this.T=w,!0):!1:!1}),l}}function X(a,b){if(!b)return b;var c=a.ja;return b.replace(/&(quot|amp|apos|lt|gt);/g,function(d,e){return c[e]}).replace(/&#(?:x([0-9a-z]{1,4})|([0-9]{1,4}));/gi,function(d,e,g){return String.fromCharCode(parseInt(e||g,e?16:10))})}
function Da(a,b){b=y(b,["script"]);if(b=ka(a,b,function(e){return"application/ld+json"===e.getAttribute("type")}))try{var c=b.textContent.replace(/^\s*<!\[CDATA\[|\]\]>\s*$/g,""),d=JSON.parse(c);c={};if(!d["@context"]||!d["@context"].match(/^https?:\/\/schema\.org$/))return c;!d["@type"]&&Array.isArray(d["@graph"])&&(d=d["@graph"].find(function(e){return(e["@type"]||"").match(this.i.Y)}));if(!d||!d["@type"]||!d["@type"].match(a.i.Y))return c;"string"===typeof d.name?c.title=d.name.trim():"string"===
typeof d.wa&&(c.title=d.wa.trim());d.C&&("string"===typeof d.C.name?c.s=d.C.name.trim():Array.isArray(d.C)&&d.C[0]&&"string"===typeof d.C[0].name&&(c.s=d.C.filter(function(e){return e&&"string"===typeof e.name}).map(function(e){return e.name.trim()}).join(", ")));"string"===typeof d.description&&(c.A=d.description.trim());d.aa&&"string"===typeof d.aa.name&&(c.D=d.aa.name.trim());return c}catch(e){a.log(e.message)}return{}}
function Ea(a,b){var c={},d={},e=/\s*(dc|dcterm|og|twitter)\s*:\s*(author|creator|description|title|site_name)\s*/gi,g=/^\s*(?:(dc|dcterm|og|twitter|weibo:(article|webpage))\s*[\.:]\s*)?(author|creator|description|title|site_name)\s*$/i;z(a,a.l.getElementsByTagName("meta"),function(h){var f=h.getAttribute("name"),l=h.getAttribute("property");if(h=h.getAttribute("content")){var k=null;l&&(k=l.match(e))&&(l=k[0].toLowerCase().replace(/\s/g,""),d[l]=h.trim());!k&&f&&g.test(f)&&h&&(l=f.toLowerCase().replace(/\s/g,
"").replace(/\./g,":"),d[l]=h.trim())}});c.title=b.title||d["dc:title"]||d["dcterm:title"]||d["og:title"]||d["weibo:article:title"]||d["weibo:webpage:title"]||d.title||d["twitter:title"];c.title||(c.title=ma(a));c.s=b.s||d["dc:creator"]||d["dcterm:creator"]||d.author;c.A=b.A||d["dc:description"]||d["dcterm:description"]||d["og:description"]||d["weibo:article:description"]||d["weibo:webpage:description"]||d.description||d["twitter:description"];c.D=b.D||d["og:site_name"];c.title=X(a,c.title);c.s=X(a,
c.s);c.A=X(a,c.A);c.D=X(a,c.D);return c}function Z(a,b){return"IMG"===b.tagName?!0:1!==b.children.length||""!==b.textContent.trim()?!1:Z(a,b.children[0])}
function Fa(a,b){var c=Array.from(b.getElementsByTagName("img"));z(a,c,function(d){for(var e=0;e<d.attributes.length;e++){var g=d.attributes[e];switch(g.name){case "src":case "srcset":case "data-src":case "data-srcset":return}if(/\.(jpg|jpeg|png|webp)/i.test(g.value))return}d.parentNode.removeChild(d)});c=Array.from(b.getElementsByTagName("noscript"));z(a,c,function(d){var e=b.createElement("div");e.innerHTML=d.innerHTML;if(Z(this,e)){var g=d.previousElementSibling;if(g&&Z(this,g)){var h=g;"IMG"!==
h.tagName&&(h=g.getElementsByTagName("img")[0]);for(var f=e.getElementsByTagName("img")[0],l=0;l<h.attributes.length;l++){var k=h.attributes[l];if(""!==k.value&&("src"===k.name||"srcset"===k.name||/\.(jpg|jpeg|png|webp)/i.test(k.value))&&f.getAttribute(k.name)!==k.value){var m=k.name;f.hasAttribute(m)&&(m="data-old-"+m);f.setAttribute(m,k.value)}}d.parentNode.replaceChild(e.firstElementChild,g)}}})}
function Ga(a,b){A(a,y(b,["script"]),function(c){c.nodeValue="";c.removeAttribute("src");return!0});A(a,y(b,["noscript"]))}function sa(a,b){var c=",";return L(a,b).split(c).length-1}
function qa(a){var b=0,c=0;a=a.getElementsByTagName("tr");for(var d=0;d<a.length;d++){var e=a[d].getAttribute("rowspan")||0;e&&(e=parseInt(e,10));b+=e||1;e=0;for(var g=a[d].getElementsByTagName("td"),h=0;h<g.length;h++){var f=g[h].getAttribute("colspan")||0;f&&(f=parseInt(f,10));e+=f||1}c=Math.max(c,e)}return{rows:b,X:c}}function ta(a,b){var c=L(a,b,!0).length;if(0===c)return 0;var d=0;b=y(b,"h1 h2 h3 h4 h5 h6".split(" "));z(a,b,function(e){return d+=L(a,e,!0).length});return d/c}
fa.prototype={I:1,J:2,H:4,ELEMENT_NODE:1,TEXT_NODE:3,ea:0,fa:5,ga:"SECTION H2 H3 H4 H5 H6 P TD PRE".split(" "),R:500,i:{Aa:/-ad-|ai2html|banner|breadcrumbs|combx|comment|community|cover-wrap|disqus|extra|footer|gdpr|header|legends|menu|related|remark|replies|rss|shoutbox|sidebar|skyscraper|social|sponsor|supplemental|ad-break|agegate|pagination|pager|popup|yom-remote/i,xa:/and|article|body|column|content|main|shadow/i,$:/article|body|content|entry|hentry|h-entry|main|page|pagination|post|text|blog|story/i,
Z:/-ad-|hidden|^hid$| hid$| hid |^hid |banner|combx|comment|com-|contact|foot|footer|footnote|gdpr|masthead|media|meta|outbrain|promo|related|scroll|share|shoutbox|sidebar|skyscraper|sponsor|shopping|tags|tool|widget/i,Ga:/print|archive|comment|discuss|e[\-]?mail|share|reply|all|login|sign|single|utility/i,s:/byline|author|dateline|writtenby|p-author/i,Ma:/<(\/?)font[^>]*>/gi,normalize:/\s{2,}/g,N:/\/\/(www\.)?((dailymotion|youtube|youtube-nocookie|player\.vimeo|v\.qq)\.com|(archive|upload\.wikimedia)\.org|player\.twitch\.tv)/i,
ya:/(\b|_)(share|sharedaddy)(\b|_)/i,Ka:/(next|weiter|continue|>([^\|]|$)|\u00bb([^\|]|$))/i,La:/(prev|earl|old|new|<|\u00ab)/i,ba:/\W+/g,Ba:/^\s*$/,ua:/\S$/,va:/^#.+/,za:/(\S+)(\s+[\d.]+[xw])?(\s*(?:,|$))/g,W:/^data:\s*([^\s;,]+)\s*;\s*base64\s*,/i,Y:/^Article|AdvertiserContentArticle|NewsArticle|AnalysisNewsArticle|AskPublicNewsArticle|BackgroundNewsArticle|OpinionNewsArticle|ReportageNewsArticle|ReviewNewsArticle|Report|SatiricalArticle|ScholarlyArticle|MedicalScholarlyArticle|SocialMediaPosting|BlogPosting|LiveBlogPosting|DiscussionForumPosting|TechArticle|APIReference$/},
la:"menu menubar complementary navigation alert alertdialog dialog".split(" "),ia:new Set("BLOCKQUOTE DL DIV IMG OL P PRE TABLE UL".split(" ")),ca:["DIV","ARTICLE","SECTION","P"],S:"align background bgcolor border cellpadding cellspacing frame hspace rules style valign vspace".split(" "),ha:["TABLE","TH","TD","HR","PRE"],ka:"ABBR AUDIO B BDO BR BUTTON CITE CODE DATA DATALIST DFN EM EMBED I IMG INPUT KBD LABEL MARK MATH METER NOSCRIPT OBJECT OUTPUT PROGRESS Q RUBY SAMP SCRIPT SELECT SMALL SPAN STRONG SUB SUP TEXTAREA TIME VAR WBR".split(" "),
da:["page"],ja:{lt:"<",gt:">",amp:"&",quot:'"',apos:"'"},pa:function(){var a=Array.prototype.slice,b=a.call(arguments).map(function(c){return a.call(c)});return Array.prototype.concat.apply([],b)},L:function(a){return a.nodeType===this.TEXT_NODE||-1!==this.ka.indexOf(a.tagName)||("A"===a.tagName||"DEL"===a.tagName||"INS"===a.tagName)&&Array.prototype.every.call(a.childNodes,this.L,this)},parse:function(){if(0<this.U){var a=this.l.getElementsByTagName("*").length;if(a>this.U)throw Error("Aborting parsing document; "+
a+" elements found");}Fa(this,this.l);a=this.qa?{}:Da(this,this.l);Ga(this,this.l);var b=this.l;A(this,y(b,["style"]));b.body&&na(this,b.body);ja(this,y(b,["font"]),"SPAN");a=Ea(this,a);this.F=a.title;b=Ca(this);if(!b)return null;this.log("Grabbed: "+b.innerHTML);ha(this,b);for(var c=b;c;){if(c.parentNode&&["DIV","SECTION"].includes(c.tagName)&&(!c.id||!c.id.startsWith("readability")))if(la(this,c)){c=H(c);continue}else if(J(this,c,"DIV")||J(this,c,"SECTION")){for(var d=c.children[0],e=0;e<c.attributes.length;e++)d.setAttribute(c.attributes[e].name,
c.attributes[e].value);c.parentNode.replaceChild(d,c);c=d;continue}c=I(c)}this.sa||ia(this,b);a.A||(c=b.getElementsByTagName("p"),0<c.length&&(a.A=c[0].textContent.trim()));c=b.textContent;return{title:this.F,s:a.s||this.O,dir:this.T,content:this.ta(b),textContent:c,length:c.length,A:a.A,D:a.D||this.ma}}};"object"===typeof module&&(module.exports=fa);
